### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by savandriy** [aino/visaxrated#1]
When I try to use the command like this:
```python
xrate('SEK', 'USD', 1.65, datetime.date(year=2016, month=05, day=16), 40)`
```
I get a Traceback:

```
Traceback (most recent call last):
  File "/home/andriy/PycharmProjects/Antest_bot/visa_mine.py", line 4, in <module>
    xrate('SEK', 'USD', 1.65, datetime.date(year=2016, month=05, day=16), 40)
  File "/usr/local/lib/python2.7/dist-packages/visaxrated/__init__.py", line 61, in xrate
    return float(div.find_all('strong')[1].text.replace(',', ''))
IndexError: list index out of range
```

I tried different currencies, but it doesn't seem to work.

**Comment by sorl** [comment]
Thanks for the report! It seems https://www.visaeurope.com/making-payments/exchange-rates only supports https now, code updated, test pass.
